version: '3.3'
services:
  web:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: php73
    volumes:
      - ./php:/var/www/html/
    ports:
      - 8000:80

  db:
    container_name: mysql8
    platform: linux/x86_64
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: root 
      MYSQL_DATABASE: db_woody
      MYSQL_USER: nono
      MYSQL_PASSWORD: mysql
    ports:
      - 6033:3306